export const translations = {
  en: {
    str: {
      menuHeader: 'Menu',
      helpHeader: 'Help',
      profileHeader: 'Profile',
      dashboardHeader: 'Dashboard',
      favoriteHeader: 'Favorite',
      settingsHeader: 'Settings',
      versionHeader: 'Version',
      titleForm: 'Authorization Form',
      usernameForm: 'Username',
      emailForm: 'Email',
      passwordForm: 'Password',
      repeatPasswordForm: 'Repeat Password',
      usernamePlaceholder: 'Enter username',
      emailPlaceholder: 'Enter email',
      passwordPlaceholder: 'Enter password',
      repeatPasswordPlaceholder: 'Repeat password',
      chooseAvatarForm: 'Choose an avatar for your profile',
      buttonRegisterForm: 'Register',
      usernameProfile: 'Username:',
      emailProfile: 'Email:',
      statusUserProfile: 'Status user:',
      subscriptionProfile: 'Subscription:',
      favoriteArtistsProfile: 'Favorite Artists:',
      favoriteTracksProfile: 'Favorite Tracks:',
      buttonChangeAvatarProfile: 'Change Avatar',
      buttonLogoutProfile: 'Logout',
      messagePlaceholderProfile: 'No messages...',
      topArtistsAside: 'Top Artists',
      followersArtistsAside: 'followers',
      dropdownValueGoProfile: 'Go to profile',
      dropdownValueAddFavorite: 'Add favorite',
      dropdownValueDeleteFavorite: 'Delete favorite',
      recentlyPlayedAside: 'Recently Played',
      searchPlaceholderDashboard: 'Search music, artist',
      titleTopMusic: 'Top Music',
      linkTopMusic: 'Show More',
      top50TopMusic: 'Top 50 Trending Music',
      titleDiscoverGenre: 'Discover Genre',
      House: 'House',
      Electronic: 'Electronic',
      Dubstep: 'Dubstep',
      'Hip-Hop/Rap': 'Hip Hop/Rap',
      Trap: 'Trap',
      'Tech House': 'Tech House',
      Pop: 'Pop',
      Latin: 'Latin',
      Electro: 'Electro',
      Techno: 'Techno',
      titleAlbum: 'Album',
      titleSortingAlbum: 'Sorting',
      titleMoodAlbum: 'Mood',
      relevantAlbum: 'Relevant',
      popularAlbum: 'Popular',
      newestAlbum: 'Newest',
      allAlbum: 'All',
      peacefulAlbum: 'Peaceful',
      fieryAlbum: 'Fiery',
      romanticAlbum: 'Romantic',
      subtitleAlbum: 'Total tracks:',
      titleListAlbum: 'Tracks by Genre:',
      titleArtistsFavorite: 'Favorite Artists',
      titleTracksFavorite: 'Favorite Tracks',
      titleArtistsListFavorite: 'List of Favorite Artists',
      subtitleArtistsListFavorite: 'Total artists:',
      titleTracksListFavorite: 'Favorite Tracks',
      nameTrack: 'Name Track:',
      genreTrack: 'Genre:',
      durationTrack: 'Duration:',
      releaseTrack: 'Release:',
      likesTrack: 'Likes:',
      buttonAddFavoriteTrack: 'Add favorite track',
      buttonDeleteFavoriteTrack: 'Delete favorite track',
      resultTypeTrack: 'track',
      resultTypeArtist: 'artist',
      titleTrack: 'CurrentTrack',
      nameArtist: 'Name Artist:',
      locationArtist: 'Location:',
      albumsArtist: 'Albums:',
      followersArtist: 'Followers:',
      tracksArtist: 'Tracks:',
      bioArtist: 'Bio:',
      buttonAddFavoriteArtist: 'Add favorite artist',
      buttonDeleteFavoriteArtist: 'Delete favorite artist',
      titleArtist: 'Artist Tracks',
      titleSettings: 'Settings',
      subtitleLangSettings: 'Language:',
      subtitleHistorySettings: 'History:',
      valueUaSetting: 'Ukrainian',
      valueEnSetting: 'English',
      valueDeleteArtists: 'Remove artists from your favorites list',
      valueDeleteTracks: 'Remove tracks from your favorites list',
      messageTitleHistory: 'History Clearing',
      artist: 'artist',
      track: 'track',
      unknown: 'unknown',
      error: 'error',
      free: 'Free',
      premium: 'Premium',
      listener: 'listener',
      blog: 'blog',
      ok: 'Ok',
      cancel: 'Cancel',
      messageTitleLang: 'Language Change',
    },
    func: {
      messageTextHistory: (type: 'artists' | 'tracks') => `Cleared favorite ${type} history`,
      messageTextLanguage: (type: 'en' | 'ua') =>
        `Language successfully changed to ${type === 'ua' ? 'Ukrainian' : 'English'}`,
    },
  },
  ua: {
    str: {
      menuHeader: 'Меню',
      helpHeader: 'Допомога',
      profileHeader: 'Профіль',
      dashboardHeader: 'Дашборд',
      favoriteHeader: 'Обране',
      settingsHeader: 'Налаштування',
      versionHeader: 'Версія',
      titleForm: 'Форма авторизації',
      usernameForm: "Ім'я користувача",
      emailForm: 'Електронна пошта',
      passwordForm: 'Пароль',
      repeatPasswordForm: 'Повторіть пароль',
      usernamePlaceholder: "Введіть ім'я користувача",
      emailPlaceholder: 'Введіть email',
      passwordPlaceholder: 'Введіть пароль',
      repeatPasswordPlaceholder: 'Повторіть пароль',
      chooseAvatarForm: 'Оберіть аватар для профілю',
      buttonRegisterForm: 'Зареєструватися',
      usernameProfile: "Ім'я користувача:",
      emailProfile: 'Електронна пошта:',
      statusUserProfile: 'Статус користувача:',
      subscriptionProfile: 'Підписка:',
      favoriteArtistsProfile: 'Улюблені виконавці:',
      favoriteTracksProfile: 'Улюблені треки:',
      buttonChangeAvatarProfile: 'Змінити аватар',
      buttonLogoutProfile: 'Вийти',
      messagePlaceholderProfile: 'Немає повідомлень...',
      topArtistsAside: 'Топ виконавців',
      followersArtistsAside: 'підписників',
      dropdownValueGoProfile: 'Перейти в профіль',
      dropdownValueAddFavorite: 'Додати в улюблене',
      dropdownValueDeleteFavorite: 'Видалити з улюбленого',
      recentlyPlayedAside: 'Нещодавно прослухані',
      searchPlaceholderDashboard: 'Пошук пісні, виконавця',
      titleTopMusic: 'Топ треків',
      linkTopMusic: 'Показати більше',
      top50TopMusic: 'Топ-50 популярних треків',
      titleDiscoverGenre: 'Огляд жанрів',
      House: 'Хаус',
      Electronic: 'Електроніка',
      Dubstep: 'Дабстеп',
      'Hip-Hop/Rap': 'Хіп-хоп/Реп',
      Trap: 'Треп',
      'Tech House': 'Тек-хаус',
      Pop: 'Поп',
      Latin: 'Латино',
      Electro: 'Електро',
      Techno: 'Техно',
      titleAlbum: 'Альбом:',
      titleSortingAlbum: 'Сортування',
      titleMoodAlbum: 'Настрій',
      relevantAlbum: 'Релевантні',
      popularAlbum: 'Популярні',
      newestAlbum: 'Новинки',
      allAlbum: 'Усі',
      peacefulAlbum: 'Спокійний',
      fieryAlbum: 'Запальний',
      romanticAlbum: 'Романтик',
      subtitleAlbum: 'Всього треків:',
      titleListAlbum: 'Треки за жанром:',
      titleArtistsFavorite: 'Улюблені виконавці',
      titleTracksFavorite: 'Улюблені треки',
      titleArtistsListFavorite: 'Список улюблених виконавців',
      subtitleArtistsListFavorite: 'Всього виконавців:',
      titleTracksListFavorite: 'Улюблені треки',
      nameTrack: 'Назва треку:',
      genreTrack: 'Жанр:',
      durationTrack: 'Тривалість:',
      releaseTrack: 'Реліз:',
      likesTrack: 'Лайки:',
      buttonAddFavoriteTrack: 'Додати в обране',
      buttonDeleteFavoriteTrack: 'Видалити з обраного',
      titleTrack: 'Поточний трек',
      nameArtist: "Ім'я виконавця:",
      locationArtist: 'Локація:',
      albumsArtist: 'Альбоми:',
      followersArtist: 'Підписники:',
      tracksArtist: 'Треки:',
      bioArtist: 'Біографія:',
      buttonAddFavoriteArtist: 'Додати до улюблених',
      buttonDeleteFavoriteArtist: 'Видалити з улюблених',
      titleArtist: 'Треки виконавця',
      titleSettings: 'Налаштування',
      subtitleLangSettings: 'Мова:',
      subtitleHistorySettings: 'Історія:',
      valueUaSetting: 'Українська',
      valueEnSetting: 'Англійська',
      valueDeleteArtists: 'Видалити виконавців зі списку улюблених',
      valueDeleteTracks: 'Видалити треки зі списку улюблених',
      free: 'Базовий',
      premium: 'Преміум',
      listener: 'слухач',
      blog: 'блог',
      ok: 'Ок',
      cancel: 'Скасувати',
      artist: 'артиста',
      track: 'трек',
      unknown: 'невідомо',
      error: 'помилка',
      resultTypeTrack: 'трек',
      resultTypeArtist: 'артист',
      messageTitleHistory: 'Очищення Історії',
      messageTitleLang: 'Мову Змінено',
    },
    func: {
      messageTextHistory: (type: 'artists' | 'tracks') =>
        `Історію улюблених ${type === 'artists' ? 'артистів' : 'треків'} очищено`,
      messageTextLanguage: (type: 'en' | 'ua') =>
        `Мову успішно змінено на ${type === 'ua' ? 'українську' : 'англійську'}`,
    },
  } as const,
};
